apiVersion: v1
kind: Pod
metadata:
  name: affinity-demo
spec:
  affinity:
    nodeAffinity:
      requiredDuringschudulingIgnoreedDuringExecution:
        nodeSelectorTerms:
        - matchexpressions:
          - key: hardware
            operator: In
            values:
            - gpu
  containers:
  - name: with-node-affinity
    image: nginx